name: 'Release'

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:

permissions:
  contents: write
  packages: write
  issues: write
  pull-requests: write
  id-token: write

jobs:
  create-release:
    runs-on: ubuntu-latest
    outputs:
      release_id: ${{ steps.create-release.outputs.id }}
      version: ${{ steps.get_version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
      - name: Get version
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT
      - name: Create release
        id: create-release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.get_version.outputs.version }}
          name: "图片批量重命名工具 v${{ steps.get_version.outputs.version }}"
          body: "请查看更改日志了解详情。"
          draft: true
          prerelease: false

  build:
    needs: create-release
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
      
      # Windows 特定配置
      - name: Setup Windows Environment
        if: matrix.platform == 'windows-latest'
        shell: pwsh
        run: |
          # 1. 更新 Chocolatey 并强制升级 NSIS
          choco upgrade chocolatey -y
          choco upgrade nsis -y --force
          
          # 2. 安装 WebView2 运行时（如果尚未安装）
          $webview2Path = "C:\Program Files (x86)\Microsoft\EdgeWebView\Application\*"
          if (-not (Test-Path $webview2Path)) {
              $webview2Url = "https://go.microsoft.com/fwlink/p/?LinkId=2124703"
              $installerPath = "$env:TEMP\MicrosoftEdgeWebview2Setup.exe"
              Invoke-WebRequest -Uri $webview2Url -OutFile $installerPath
              Start-Process -FilePath $installerPath -Args "/silent /install" -Wait
          }
          
          # 3. 验证工具链
          rustup target add x86_64-pc-windows-msvc
          rustup show

      # macOS 特定配置
      - name: Setup macOS Rust
        if: matrix.platform == 'macos-latest'
        uses: dtolnay/rust-toolchain@stable

      - name: Install app dependencies
        run: npm install

      - name: Build Tauri App
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_PRIVATE_KEY: ${{ secrets.TAURI_PRIVATE_KEY }}
          TAURI_KEY_PASSWORD: ${{ secrets.TAURI_KEY_PASSWORD }}
        shell: pwsh
        run: |
          if ('${{ matrix.platform }}' -eq 'macos-latest') {
            npm run tauri build
          } else {
            # Windows 构建明确指定目标
            npx tauri build --target x86_64-pc-windows-msvc
          }

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: release-${{ matrix.platform }}
          path: |
            src-tauri/target/release/*.dmg
            src-tauri/target/release/*.app.tar.gz
            src-tauri/target/release/*.msi
            src-tauri/target/release/*.exe

  publish-release:
    needs: [create-release, build]
    runs-on: ubuntu-latest
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Publish release
        uses: softprops/action-gh-release@v1
        with:
          draft: false
          files: |
            artifacts/release-macos-latest/*.dmg
            artifacts/release-macos-latest/*.app.tar.gz
            artifacts/release-windows-latest/*.msi
            artifacts/release-windows-latest/*.exe